### ISSUE TITLE
Trial anonymizing NRM production data to produce appropriate test database

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#102]
**Background**
We want to explore ways of anonymizing NRM production data in our prototyping environment. Given the complexity of the G&A app, we want to make sure that we can produce an appropriate test database that lets us prototype complicated test cases and data relationships.  

**We'll know we're done when...**
- [ ] We have determined an approach for anonymizing NRM production data in our test database that is adequately anonymized, but also valuable for our prototyping efforts.

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
Rough outline of current thinking: 
1. Use Django's `dumpdata` to create a CSV fixture of the current DB tables.
2. Manipulate those fixtures outside of the DB, outside of the repo with Faker as outlined on https://medium.com/district-data-labs/a-practical-guide-to-anonymizing-datasets-with-python-faker-ecf15114c9be (especially the Anonymizing CSV Data bit)
3. Load the manipulated data as fixtures using `loaddata`, both locally and on prod.
