### ISSUE TITLE
USFS USWDS color mapping

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#105]
**Background**
The new G&A application will use USWDS, and we'll want to match the FS branding. [The FS flagship site ](https://www.fs.usda.gov/) recently upgraded to USWDS2, and is using USWDS color tokens.

We'd like to learn more about their mapping so that we can leverage it for this project.

**We'll know we're done when...**
- [x] We've got a USWDS2 color mapping to get started

**Tasks**
- [x] See if we can get the FS site's USWDS theme file
   - [USWDS theme files](https://drive.google.com/drive/folders/1RSHOk2USWiJxqq1mOmfbSDb9XmLR8W6T) from https://www.fs.usda.gov/
   - [Automated styleguide](https://cms.fs.usda.gov/simple-styleguide) via Drupal from fs.usda.gov (requires FS VPN)
   - [USFS Digital playbook by EAD](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/), uses USWDS1 (requires FS VPN)
   - [Notes from conversation](https://docs.google.com/document/d/1U-Auozuf2XSIHHdi6NPK7X7FjqIxNeEe6SuDq4zamEI/edit#heading=h.xn5wobrdvd1y)

**Comment by allisonnorman** [comment]
Note from Mural: "I think this can come later if design feels overloaded; we can design with USWDS defaults and keep things low fidelity"

**Comment by cmajel** [comment]
Reached out to past contact from the FS site team 🤞
