### ISSUE TITLE
Investigate prettier grant text display

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#110]
**Background** The oracle database represented almost all fields as all caps. It would be nice if we could present a nicer output (title case) without changing the DB representation.

**We'll know we're done when...**
- [ ] We've developed methods to produce prettier representation of grant fields 
OR
- [ ] We've documented why it's not going to work.

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
@neilmb unless you've got some ideas you'd like to see us try, I think we need to icebox this. 

* Manipulating `__str__` isn't providing any meaningful improvement.
* We could write a custom method, but until we're writing custom pages to use it, it won't be called.
* Forms are going to show the DB version anyway, and I don't think there's much we can do there.
* It would largely resolve itself for new agreements, since there's no incentive to all caps things anymore.

**Comment by neilmb** [comment]
I'm fine to icebox this. Is there a link to a dead-end branch with things that we tried that didn't work that we want to put on this issue?

**Comment by tbaxter-18f** [comment]
Disregard. I forgot to update this, but I figured it out and a fix will go in with https://github.com/18F/NRM-Grants-Agreements/pull/134/files

**Comment by tbaxter-18f** [comment]
Resolved with the merge of https://github.com/18F/NRM-Grants-Agreements/pull/134
