### ISSUE TITLE
Synthesize and document harms

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#122]
**Background**
Based on the activity in last week's workshop (#59), we want to revisit the harms as a team to fill in additional details as well as find a home for documenting these outside of the [workshop mural](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87).

**We'll know we're done when...**
- [x] We have met as a team to fill in any blanks.
- [x] We know where these will live (wiki? Service blueprint?)

**Tasks**
- [ ] 
- [ ]

**Comment by allisonnorman** [comment]
@cmajel How much work do you think is left here? Or is it a matter of connecting this back to the service blueprint? Let me know if we should close this out and create something else or if we should push it to sprint 4. Thanks!

**Comment by cmajel** [comment]
@allisonnorman @MelissaBraxton I did a pass at synthesizing these within the [hypotheses / harms mural we created](https://app.mural.co/t/gsa6/m/gsa6/1615999416414/f254ed34fd3d94b17d369e5d6ee374eb92365ea4). It's still not clear to me if this should be the final home for this.

I think the answer is our future state blueprint #118? Does that feel right to folks?

**Comment by allisonnorman** [comment]
Yes, that feels right to me!

**Comment by allisonnorman** [comment]
I added a task in #118 re: harms. I'll go ahead and close this.
