### ISSUE TITLE
Plan next user research focus area

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#171]
**Background**
In sprint 5, we should think about what opportunities there are to get feedback from users around our prototyping focus, specifically around user story #184:
- the proposal creation form (both the required fields as well as some of the ideas of what the form could include beyond that, if we deem that valuable) 
- how we could start to get some feedback on a commitment approval workflow before building that into the prototype (user story: #169)

This issue is closely related:  Mock up an agreement creation form for budget approver story #173

Other related issues: 
- Mock up a new agreement creation form #153
- As-is workflow model for pre-award processes #162
- As a Budget Approver, I need to see which commitments requests from a new proposal or modification that I need to approve. #169
- Scope agreement creation and approval workflow prototyping #152

**We'll know we're done when...**
- [x] We have a focus area for our next round of user research.
- [x] We've created issues around next steps. 

**Tasks**
- [ ] 
- [ ]

**Comment by MelissaBraxton** [comment]
Based on strategy discussion, we're tragetting agreement creation mocks and updated dashboard concept for user research in sprint 6.
