### ISSUE TITLE
Django admin app showing up w/ a black screen for some folks 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#186]
**Background**
Melissa is seeing the Django admin app, show up in some kind of dark mode when logged in as the test user. 

**We'll know we're done when...**
- [ ] Melissa logs into the Django admin app and it's readable and renders as designed. 
- [ ] We've documented any relevant insights or instructions on how to make sure it doesn't happen again. 

**Tasks**
- [ ] 
- [ ]

**Comment by MelissaBraxton** [comment]
![Uploading Screen Shot 2021-04-12 at 11.57.16 AM.png…]()

**Comment by tbaxter-18f** [comment]
Two questions:

1. If you log in with an incognito window do you still see it?
2. If you log in with a different user, do you still see it?

**Comment by MelissaBraxton** [comment]
1. Yes
2. Yes

**Comment by tbaxter-18f** [comment]
OK, can you view source and see if you see:

<link href="/static/css/site.css?v=2" rel="stylesheet" type="text/css"> (in particular, the v=2)

Can you go to https://fs-nrm.app.cloud.gov/static/css/site.css and force refresh?

And if that doesn't work, will you right click and inspect one of the black-background areas and see if you can see where it's inheriting the dark color value from?

**Comment by MelissaBraxton** [comment]
<img width="548" alt="Screen Shot 2021-04-14 at 1 44 40 PM" src="https://user-images.githubusercontent.com/20651166/114776980-f6830880-9d27-11eb-841f-e070aeaf65ea.png">

Looks like it's the dark mode. I changed it to light and it works fine! 

Probably something we still need to fix though if the effort is low, since some usability test participants may also be using dark mode.

**Comment by tbaxter-18f** [comment]
That's fantastic, @MelissaBraxton. Thanks for diving in and finding that. I'll get a PR out ASAP.

**Comment by tbaxter-18f** [comment]
I'm thinking that our CSS is likely to diverge further from the default Django styles, and until we come to a time when we're prepared to design intentionally for dark mode we should remove it and have a single set of styles. Any objection?

**Comment by MelissaBraxton** [comment]
LGTM!
