### ISSUE TITLE
Understand and Draw the Infrastructure of the G&A System

### ISSUE THREAD

**Issue by donnykwan** [18F/NRM-Grants-Agreements#23]
**Background**
Understand what G&A is running on, server, applications, network, API, middleware, info security, etc.

**Acceptance Criteria**

- [x] Talk to IT folks
- [x] Draw the architecture diagram

**Comment by neilmb** [comment]
![image005](https://user-images.githubusercontent.com/443389/101960592-698b3f80-3bcd-11eb-853d-8ecbf0d022e3.png)

That's the last piece, together with https://docs.google.com/drawings/d/1jByxnsb1bcISNdc2Lmuaiq198zp5_1gMVrtpg1RyiRA
