### ISSUE TITLE
Understand and Tell the G&A Applications Processes (User Stories)

### ISSUE THREAD

**Issue by donnykwan** [18F/NRM-Grants-Agreements#24]
**Background**
Understand how users are using the app.

Users: Grant Specialists, Program Manager, Financial Approver, ??, grants applicants 

Process: Pre-award, Application (Grant, MOU agreements, Incoming funds agreements, ??), Modifications, Review and Approval,  Project update, Project Closure, ??)

**Acceptance Criteria**
- [ ] Talk to stakeholders
- [ ] At least to have a compete process view for the Grant application, modification, project update, project closure.

**Comment by MelissaBraxton** [comment]
There's a shell of this in Mural that we can build off of [here](https://app.mural.co/t/gsa6/m/gsa6/1606250486487/cbe51bccb556bebc4b12c9b98c8201e6cdcea6c3).

**Comment by MelissaBraxton** [comment]
We can close this out since it's covered under #33 and #36 for now.
