### ISSUE TITLE
Pair with FS product team on a round of discovery research

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#284]
**Background**

To demonstrate that FS is ready to use design research on this project, we should consult with them while the G&A development team perform a round of design research. Design staff will likely come from the vendor and we will assist and coach the product owner and project manager in preparing, conducting, and documenting the research

**We'll know we're done when...**
- [ ] The G&A development team has conducted a round of research and documented their results 
- [ ] We have reflected with the G&A development team on their research process and how it can go better 

**Tasks**
- [ ] 
- [ ]

**Comment by cmajel** [comment]
Closing this out for now, as we've done this on a few past research cycles. cc @19mderose @MelissaBraxton
