### ISSUE TITLE
Advocate for tech lead responsibilities within FS personnel

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#290]
**Background**

18F's modular acquisitions approach depends on strong product ownership inside the government, but also technical capabilities for accepting code from vendors, aligning architectural decisions with agency standards, and preparing security and compliance documentation. Those responsibilities need to be accounted for within the product team and there are some questions about where those responsibilities need to be performed by government employees vs. contractors.

**We'll know we're done when...**
- [ ] We have documented our recommendations for tech lead responsibilities
- [ ] We have discussed with the FS possible solutions for getting those jobs done

**Tasks**
- [ ] 
- [ ]

**Comment by cmajel** [comment]
@neilmb should this change based on staffing changes at FS?

**Comment by neilmb** [comment]
I think that we could close this because we have https://github.com/USDAForestService/NRM-Grants-Agreements/issues/331 to onboard the tech lead to what the role entails.
