### ISSUE TITLE
Review QASP and its application with product owner

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#292]
**Background**

Part of vendor management is knowing what is in the Quality Assurance Surveillance Plan (QASP) and how to use those elements to accept work from the vendor.

**We'll know we're done when...**
- [ ] We have done a session with the product owner talking through the QASP for the vendor contract

**Tasks**
- [ ] Identify who at FS will be involved in QASP monitoring (or should get training)
- [ ]

**Comment by jayrbergjr** [comment]
I'm open to do this anytime.

**Comment by neilmb** [comment]
Should invite Jay, Adam, and Magdaline at least.

**Comment by neilmb** [comment]
Meeting set for August 19th.

**Comment by neilmb** [comment]
This meeting happened and went well. https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Release-Engineering-Process has the QASP and notes on how we are implementing the automated portions of it.
