### ISSUE TITLE
Page load error with multiple categories on grant

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#319]
Django throws a MultipleObjectsReturned error for grants that are associated with multiple categories.

**Reproduction steps**

1. Visit /admin/grants/grant/6020529010602/change/

**Expected**

The grant change page for this grant loads.

**Actual**

Error page with:

```
MultipleObjectsReturned at /admin/grants/grant/6020529010602/change/
  get() returned more than one Category -- it returned 4!
```

**Additional context**

In the Python shell, I confirmed that this grant is associated with four categories.

**Possible solution**

I'm thinking we need to either enforce a one-category constraint, or use `filter` instead of `get` for loading associated categories.

**Comment by neilmb** [comment]
Closing as this is specific to the abandoned Django prototype
