### ISSUE TITLE
Onboard USFS tech lead

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#331]
18F typically brings goverment-side technical leadership during our engagements, but we're not here for the long haul, so we need to make sure someone at USFS is well prepared to fill this role when we go. To that end, this issue covers how we'll help the USFS tech lead get to know this work so that they can achieve these goals re: resilience, security, and transparency:

### Tech lead goals

**Make the product resilient.**

Government should be able to keep the product running after the vendor rolls off. If vendors change, vendor personnel changes, or other unforseen changes happen -- the Tech Lead can help the project stay strong & resilient!
 
**Keep the product secure.**
The Tech Lead can help keep the product secure by reviewing code, managing access to apps, and responding to incidents if they arise.
 
**Keep government fully aware of changes so that gov't gets the product it wants & needs.**
The Tech Lead can help be government "eyes and ears" to make sure that the government is getting the technical product it is contracting and paying for.

**Current team to-dos**
- [x] Confirm roles in wiki are up-to-date, and add new team member to team list.
- [x] Send invite to Slack channel (#usfs-ga-partners).
- [x] Send invite to [Github repo](https://github.com/USDAForestService/NRM-Grants-Agreements/settings/access).
- [x] [Share access to Google Drive project folder](https://drive.google.com/drive/folders/1QryiLPQ2Z8IXKYaDp9mlRJxkDr5kPHw9).
- [x] Send invite to [G&A Mural room](https://app.mural.co/t/gsa6/r/1612999180491).
- [x] ~Send invite to [google group](https://groups.google.com/a/gsa.gov/g/18f-usfs-nrm)/distro list (18f-usfs-nrm@gsa.gov)~.
- [x] Send invites to weekly meetings.
- [x] Schedule intro meeting with FS product owner Product Manager.

**Give a tour of:** 
- [x] historical project docs (PA report, tech solutions doc, etc.)
- [x] transition plan
- [x] skill area heuristics documentation
- [x] tech Lead role documentation
- [x] strategy docs
- [x] roadmap in Mural (deep dive)
- [x] design assets
- [x] data model
- [x] codebase
- [x] current prototype
- [x] schedule roadmap deep dive
- [X] schedule eng  deep dive

**Adam's onboarding checklist**
- [x] Review project charter
- [x] Schedule coffees with the team to talk through their work and to get to know each other
- [x] Get an account for any new-to-you tools (we use Github, Mural, and Zenhub).
- [x] Review [artifact library](https://docs.google.com/document/d/1hxeQfYv25ohCHboFprqk1C5rKiVys3GWnh_uxZEDB-k/edit#) , Google Drive, and other project spaces.

**Comment by neilmb** [comment]
Google groups are apparently GSA-only, so we can't add Adam to the 18f-usfs-nrm@gsa.gov group.

**Comment by neilmb** [comment]
Meeting August 17th to finish this off (hopefully).

**Comment by neilmb** [comment]
Good meeting, we finished reviewing various documents. @AdamUSDA can you do the last two things on the bottom of the list, then check them off, and close this issue?

**Comment by AdamUSDA** [comment]
Hello @neilmb 

Can you share the Project Charter with me.

**Comment by neilmb** [comment]
All done, everything checked off.
