### ISSUE TITLE
Journey map

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#36]
**Background**

**Acceptance criteria** 
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by MelissaBraxton** [comment]
Sent a draft on 1/29. Waiting for feedback.

**Comment by cmajel** [comment]
Blocked/waiting until our planned 2/26 review with Jay and Jamie
