### ISSUE TITLE
Find out whether Pega would need to be ATO'd at USFS

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#49]
**Background**
This follow up on a Q that came up in one of our weekly sponsor syncs. There's a Q of whether use of Pega could be fastracked becuse it's ATO'd at USDA and the timeing and effort assoc. with this factors in to our SWOT of different approaches. 

**We'll know we're done when** 
- [x] We've documented what is known about whether Pega would need it's own ATO and the implications on O&GA getting a new grants management solution from Pega.

**Tasks**
- [x] Find out who can tell us whether Pega would need an ATO
- [x] Schedule meeting
- [x] Document finding

**Comment by MelissaBraxton** [comment]
Emailed Laura on 2/5. Moving into blocked/waiting while we await a response.

**Comment by MelissaBraxton** [comment]
Response from Laura at USFS: 

_Hello, thanks for the reach out. I have looped in Robert Chadderdon  and Chris Collett my ATO SMEs that can answer some of your questions below regarding the need for a new ATO. So they should be able to provide you the guidance necessary to understand what will need to be done – I believe that we will need to have another ATO completed for this new Pega platform and not sure if any of the existing artifacts from the current ATO supporting the legacy G&A system can be repurposed. They can provide you that information as well.  Respectfully, Laura_

**Comment by MelissaBraxton** [comment]
@neilmb  - Can we roll this in to the call you're having to chat about the prototype? If so, maybe you should take the lead on this /assign yourself?

**Comment by neilmb** [comment]
Yes, I will ask about it.

**Comment by neilmb** [comment]
We talked about this today with Hieu Nguyen the ISSO for NRM today and Mona Rayside from their security development team.

- They said that separating NRM G&A out from the existing NRM legacy application would require re-writing the SSP for G&A to stand alone.
-  If the new G&A uses a platform that isn't already used for something inside of FS, then documenting the controls for the new system could take LOTS of time as they have to get the information for how each control is satisfied
- If the platform used for the new G&A application is FedRAMP moderate, then they can inherit many of the controls from that platform's FedRAMP approval. But, there are some details to pay attention to about how the actual instances are set up versus what is on FedRAMP.

Pega Cloud is FedRAMP Moderate but has never been used for anything before at FS, as far as we know.
