### ISSUE TITLE
Acquire and inspect DB

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#69]
In order to prototype we should have a good sense of what the existing data looks like. Ideally, this would be a DB dump. Failing that, a good set of representative test data may have to suffice.

We'll know we're done when:
* Data has been acquired
* We have taken a good look at it and understand what's what and how it interconnects.
* We know what types of PII, controlled, and classified data exists in the DB and systems and what potential concerns we should note heading into prototyping.
* We know of any data that is controlled or classified in the G&A and NRM DB/systems.

Bonus: 
* Run Django's inspectDB to generate models

Gotchas:
* Because it appears to use (per the ERD) weird Oracle field types, we need to be careful to mirror the constraints so we don't introduce any defects.

**Comment by tbaxter-18f** [comment]
@neilmb has begun inquiries about a DB dump.

**Comment by neilmb** [comment]
I have a connection to the Oracle database, but I'm waiting on username and password things.

**Comment by neilmb** [comment]
I have a username and password now. I'm working on the best way to extract the data from the database tables.

**Comment by neilmb** [comment]
We are trying out exporting data using SQLWorkbench/J on the FS laptop overnight to see just how slow it is. We'll check in then to see if we need to come up with a better option.

**Comment by tbaxter-18f** [comment]
@neilmb do you think we should create tasks for each table we want to pull and inspect (and review), or use this issue for the grants table and log separate issues for the other tables?

It kinda feels like pulling all the tables in may be a bit much for one issue. I definitely don't think we'll want one monolithic review for all of them.

**Comment by allisonnorman** [comment]
I reconciled this with #58 (as discussed in stand) and added a couple more "we'll know we're done" items from that issue here.

**Comment by tbaxter-18f** [comment]
PR #84 includes three tables, viewable in the Django admin
