### ISSUE TITLE
Decide what design system we want to use for prototyping

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#77]
**Background**

**Acceptance criteria** 
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  
- [ ]

**Comment by tbaxter-18f** [comment]
My thought (reflected in #74) was that we would use the FS fork. Is there something else to consider?

**Comment by allisonnorman** [comment]
Decision: USWDS 2.0! (Discussion [here](https://gsa-tts.slack.com/archives/C01LDBVCF8A/p1614028830016700))
